server:
  port: 9000
  servlet:
    context-path: /conformity-gateway

spring:
  application:
    name: conformity-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.170.21.199:8848,192.170.21.167:8850,192.170.21.192:8852
        namespace: spring-cloud-conformity
        group: spring-cloud-conformity
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了
      routes:
        - id: conformity-web
          uri: lb://conformity-web
          predicates:
            - Path=/conformity-web/**