server:
  port: 18080
  servlet:
    context-path: /conformity-web

spring:
  application:
    name: conformity-web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://192.170.21.192:3306/spring_cloud_conformity?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      #配置初始化大小、最小、最大线程数
      initial-size: 5
      min-idle: 5
      #CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
      max-active: 20
      # 最大等待时间，内网：800，外网：1200（三次握手1s）
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最大空间时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      # 设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      test-on-borrow: true
      # 设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      test-on-return: true
      #可以支持PSCache（提升写入、查询效率）
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall:用于防火墙
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
        wall:
          config:
            multi-statement-allow: true

  cloud:
    nacos:
      discovery:
        server-addr: 192.170.21.199:8848,192.170.21.167:8850,192.170.21.192:8852
        namespace: spring-cloud-conformity
        group: spring-cloud-conformity
        username: nacos
        password: nacos